//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackOrder()
        {
            this.BackOrderLines = new HashSet<BackOrderLine>();
        }
    
        public int BackOrderID { get; set; }
        public int BackOrderStatusID { get; set; }
        public int SupplierOrderID { get; set; }
        public int QuantityOutstanding { get; set; }
    
        public virtual BackOrderStatu BackOrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackOrderLine> BackOrderLines { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
    }
}
