//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRentalLine
    {
        public int StockID { get; set; }
        public string CustomerRentalID { get; set; }
        public int PriceID { get; set; }
    
        public virtual CustomerRental CustomerRental { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
