//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GradStockUpEntities : DbContext
    {
        public GradStockUpEntities()
            : base("name=GradStockUpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<BackOrder> BackOrders { get; set; }
        public virtual DbSet<BackOrderLine> BackOrderLines { get; set; }
        public virtual DbSet<BackOrderStatu> BackOrderStatus { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<CheckInLaundry> CheckInLaundries { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerRental> CustomerRentals { get; set; }
        public virtual DbSet<CustomerRentalLine> CustomerRentalLines { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryStatu> DeliveryStatus { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<Establishment> Establishments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyQualification> FacultyQualifications { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstitutionFaculty> InstitutionFaculties { get; set; }
        public virtual DbSet<INSTITUTIONLINE> INSTITUTIONLINEs { get; set; }
        public virtual DbSet<InstitutionLineQualification> InstitutionLineQualifications { get; set; }
        public virtual DbSet<LaundryLine> LaundryLines { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<OnlineOrder> OnlineOrders { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Outfit> Outfits { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<QualificationType> QualificationTypes { get; set; }
        public virtual DbSet<RefundStatu> RefundStatus { get; set; }
        public virtual DbSet<ReturnFromLaundry> ReturnFromLaundries { get; set; }
        public virtual DbSet<ReturnLine> ReturnLines { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockDescription> StockDescriptions { get; set; }
        public virtual DbSet<StockQualification> StockQualifications { get; set; }
        public virtual DbSet<StockReturn> StockReturns { get; set; }
        public virtual DbSet<StockReturnLine> StockReturnLines { get; set; }
        public virtual DbSet<StockState> StockStates { get; set; }
        public virtual DbSet<StockType> StockTypes { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierOrder> SupplierOrders { get; set; }
        public virtual DbSet<SupplierOrderLine> SupplierOrderLines { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WriteOff> WriteOffs { get; set; }
        public virtual DbSet<WriteOffLine> WriteOffLines { get; set; }
    }
}
