//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnLine
    {
        public int ReturnID { get; set; }
        public int StockID { get; set; }
        public int CheckInLaundryID { get; set; }
    
        public virtual CheckInLaundry CheckInLaundry { get; set; }
        public virtual ReturnFromLaundry ReturnFromLaundry { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
