//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrderLine
    {
        public int StockDescriptionID { get; set; }
        public int SupplierOrderID { get; set; }
        public int Quantity { get; set; }
    
        public virtual StockDescription StockDescription { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
    }
}
