//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradStockUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOrderLine
    {
        public int StockDescriptionID { get; set; }
        public int BackOrderID { get; set; }
        public int Quantity { get; set; }
    
        public virtual BackOrder BackOrder { get; set; }
        public virtual StockDescription StockDescription { get; set; }
    }
}
