//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradStockUp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerRentals = new HashSet<CustomerRental>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.OnlineOrders = new HashSet<OnlineOrder>();
        }
        public int CustomerID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        [Required]
        [Display(Name = "Name")]
        [MaxLength(20, ErrorMessage = "Name must be 20 characters. ")]
        public string CustomerName { get; set; }
        [Required]
        [Display(Name = "Surname")]
        [MaxLength(20, ErrorMessage = "Surname must be 20 characters. ")]
        public string CustomerSurname { get; set; }
        [Required]
        [Display(Name = "Address")]
        [MaxLength(100, ErrorMessage = "Address is too long. ")]
        [DataType(DataType.MultilineText)]
        public string CustAddress { get; set; }
        [Required]
        [Display(Name = "Identification")]
        [MinLength(9, ErrorMessage = "Please enter a valid Identification Number.")]
        [MaxLength(13, ErrorMessage = "Please enter a valid Identification Number.")]
        [DisplayFormat]
        public string IDnumber { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [MaxLength(100, ErrorMessage = "Email Address too long. Try a different one. ")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        [MinLength(10, ErrorMessage = "Phone number must be 10 digits.")]
        [MaxLength(10, ErrorMessage = "Phone number must be 10 digits.")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }
        [Required]
        [Display(Name = "Nex of Kin Name")]
        [MaxLength(50, ErrorMessage = "Enter a shorter name .")]
        public string NextoFKin { get; set; }
        [Required]
        [Display(Name = "Nex of Kin Contact")]
        [MinLength(10, ErrorMessage = "Phone Number must be 10 digits.")]
        [MaxLength(10, ErrorMessage = "Phone number must be 10 digits.")]
        [DataType(DataType.PhoneNumber)]
        public string kinPhone { get; set; }
      
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRental> CustomerRentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineOrder> OnlineOrders { get; set; }
    }
}
