//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradStockUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRental()
        {
            this.CustomerRentalLines = new HashSet<CustomerRentalLine>();
            this.StockReturns = new HashSet<StockReturn>();
        }
    
        public string CustomerRentalID { get; set; }
        public int CustomerID { get; set; }
        public int OrderStatusID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public int PaymentMethodID { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public decimal AmountPaid { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRentalLine> CustomerRentalLines { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReturn> StockReturns { get; set; }
    }
}
