//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradStockUp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Customers = new HashSet<Customer>();
        }
        public int OrganizationID { get; set; }
       
        public string Name { get; set; }
        [Required]
        [Display(Name = "Org. Name")]
        [MaxLength(100, ErrorMessage = "Organization name is too long.")]
        public string Address { get; set; }
        [Required]
        [Display(Name = "Org. Address")]
        [MaxLength(100, ErrorMessage = "Organization Address is too long.")]
        [DataType(DataType.MultilineText)]
        public string Contact { get; set; }
        [Required]
        [Display(Name = "Org. Phone")]
        [MaxLength(10, ErrorMessage = "Phone number must be 10 digits.")]
        [MinLength(10, ErrorMessage = "Phone number must be 10 digits.")]
     
        public string RegistrationNO { get; set; }
        [Required]
        [Display(Name = "Org. Registration No.")]
        [MaxLength(50, ErrorMessage = "Registration Number is too long.")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
