//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradStockUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.CustomerRentalLines = new HashSet<CustomerRentalLine>();
            this.LaundryLines = new HashSet<LaundryLine>();
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            this.ReturnLines = new HashSet<ReturnLine>();
            this.StockReturnLines = new HashSet<StockReturnLine>();
            this.WriteOffLines = new HashSet<WriteOffLine>();
        }
    
        public int StockID { get; set; }
        public int StockStatusID { get; set; }
        public int StockDescriptionID { get; set; }
        public int StockStateID { get; set; }
        public int LocationID { get; set; }
        public int DepartmentID { get; set; }
        public string ImageName { get; set; }
        public byte[] BarcodeImage { get; set; }
        public string StockBarcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRentalLine> CustomerRentalLines { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaundryLine> LaundryLines { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnLine> ReturnLines { get; set; }
        public virtual Status Status { get; set; }
        public virtual StockDescription StockDescription { get; set; }
        public virtual StockState StockState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReturnLine> StockReturnLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriteOffLine> WriteOffLines { get; set; }
    }
}
